In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Bank Marketing Data/Bank_Marketing_Original_Data.csv')

In [3]:
df.head()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        45211 non-null  int64
 1   Job        45211 non-null  str
 2   Marital    45211 non-null  str
 3   Education  45211 non-null  str
 4   Default    45211 non-null  str
 5   Balance    45211 non-null  int64
 6   Housing    45211 non-null  str
 7   Loan       45211 non-null  str
 8   contact    45211 non-null  str
 9   Day        45211 non-null  int64
 10  Month      45211 non-null  str
 11  Duration   45211 non-null  int64
 12  Campaign   45211 non-null  int64
 13  Pdays      45211 non-null  int64
 14  Previous   45211 non-null  int64
 15  poutcome   45211 non-null  str
 16  TARGET     45211 non-null  str
dtypes: int64(7), str(10)
memory usage: 5.9 MB

In [5]:
## for standard scaler
from sklearn.preprocessing import StandardScaler

In [6]:
ss= StandardScaler()

In [9]:
ss.fit_transform(df[['Age']])

array([[ 1.60696496],
       [ 0.28852927],
       [-0.74738448],
       ...,
       [ 2.92540065],
       [ 1.51279098],
       [-0.37068857]], shape=(45211, 1))

In [11]:
numerical_columns=df[['Age','Balance','Day','Duration','Campaign','Pdays','Previous']]

In [12]:
numerical_columns

       Age  Balance  Day  Duration  Campaign  Pdays  Previous
0       58     2143    5       261         1     -1         0
1       44       29    5       151         1     -1         0
2       33        2    5        76         1     -1         0
3       47     1506    5        92         1     -1         0
4       33        1    5       198         1     -1         0
...    ...      ...  ...       ...       ...    ...       ...
45206   51      825   17       977         3     -1         0
45207   71     1729   17       456         2     -1         0
45208   72     5715   17      1127         5    184         3
45209   57      668   17       508         4     -1         0
45210   37     2971   17       361         2    188        11

[45211 rows x 7 columns]

In [13]:
ss.fit_transform(numerical_columns)

array([[ 1.60696496,  0.25641925, -1.29847633, ..., -0.56935064,
        -0.41145311, -0.25194037],
       [ 0.28852927, -0.43789469, -1.29847633, ..., -0.56935064,
        -0.41145311, -0.25194037],
       [-0.74738448, -0.44676247, -1.29847633, ..., -0.56935064,
        -0.41145311, -0.25194037],
       ...,
       [ 2.92540065,  1.42959305,  0.14341818, ...,  0.72181052,
         1.43618859,  1.05047333],
       [ 1.51279098, -0.22802402,  0.14341818, ...,  0.39902023,
        -0.41145311, -0.25194037],
       [-0.37068857,  0.52836436,  0.14341818, ..., -0.24656035,
         1.4761376 ,  4.52357654]], shape=(45211, 7))